[package]
name = "zera-program"
version.workspace = true
edition.workspace = true

[dependencies]
solana-program = "1.18.26"
spl-token = { version = "4.0.2", features = ["no-entrypoint"] }
borsh = "1.5"
thiserror = "1.0"
zera-shared = { path = "../shared" }

[lib]
crate-type = ["cdylib", "lib"]
